#!/bin/bash

declare -a NP=("1" "2" "5" "8" "10")

declare -a args=("500 0 0")

module load spectrum_mpi/
module load cuda
module load autoload openblas/

#make
#for ((i=0; i<${#NP[@]}; i++))
#do
#    for ((j=0; j<${#args[@]}; j++))
#    do
#	make run NP="${NP[$i]}" ARGS="${args[$j]}"
#    done
#done

make clean
make USE_CBLAS=1
for ((i=0; i<${#NP[@]}; i++))
do
    for ((j=0; j<${#args[@]}; j++))
    do
        make run NP="${NP[$i]}" ARGS="${args[$j]}"
    done
done
make clean USE_CBLAS=1
make USE_GPU=1
for ((i=0; i<${#NP[@]}; i++))
do
    for ((j=0; j<${#args[@]}; j++))
    do
        make run NP="${NP[$i]}" ARGS="${args[$j]}"
    done
done
make clean USE_GPU=1
