#!/bin/bash

declare -a NP=("1" "2" "5" "8" "10")

declare -a args=("1000 100" "1000 1000" "5000 100" "5000 1000" "10000 100" "10000 1000")

declare -a ref=("0")

for ((i=0; i<${#NP[@]}; i++))
do
    for ((j=0; j<${#args[@]}; j++))
    do
	for ((k=0; k<${#ref[@]}; k++))
	do
	    make run NP="${NP[$i]}" ARGS="${args[$j]}" ID_REF="${ref[$k]}"
	done
    done
done
	   
